
cmake_minimum_required(VERSION 3.21)

project(test)

set(AUTOC_MODULE_NAME test)
set(AUTOC_MODULE_SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/${AUTOC_MODULE_NAME}.py)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake)

include(AutoC)

add_autoc_module(
  ${AUTOC_MODULE_NAME}
  DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
  MAIN_DEPENDENCY ${AUTOC_MODULE_SOURCE}
  COMMAND ${Python_EXECUTABLE} ${AUTOC_MODULE_SOURCE} ${AUTOC_MODULE_NAME}
)

add_executable(${PROJECT_NAME} ${PROJECT_NAME}.c)
set_property(TARGET ${PROJECT_NAME} PROPERTY C_STANDARD 11 C_STANDARD_REQUIRED ON)
#set_source_files_properties(test.c PROPERTIES LANGUAGE CXX)
target_link_libraries(${PROJECT_NAME} ${AUTOC_MODULE_NAME}-auto)