require 'finita/common'
require 'finita/symbolic'
require 'finita/problem'
require 'finita/system'
require 'finita/equation'
require 'finita/generator'
require 'finita/backend'
require 'finita/cell'