require 'finita/type'
require 'finita/evaluator'
require 'finita/problem'
require 'finita/system'
require 'finita/equation'
require 'finita/solver'
require 'finita/discretizer'
require 'finita/mapper'